local cfg = {
  core = {
    minimal = false,
    lsp = true,
    allow_sudo_write = true,
    use_ai_completion = false,
    use_treesitter = true,
    notify_about_indentation = true,
    use_git = true,
    use_templates = true,
    scrollbar = true,
    dashboard = true,
    color_picker = false,
  },

  enabled_lsps = {},

  env = {
    using_kitty = true,
    using_nerd_font = true,
  },

  appearance = {
    colorscheme = "kanagawa",
    transparent_background = false,
  },

  icons = {
    diagnostics = {
      Error = " ",
      Warn = " ",
      Hint = "󰌵 ",
      Info = " ",
    },
    git = {
      added = " ",
      modified = " ",
      removed = " ",
    },
    kinds = {
      Array = " ",
      Boolean = " ",
      Class = " ",
      Color = " ",
      Constant = " ",
      Constructor = " ",
      Copilot = " ",
      Enum = " ",
      EnumMember = " ",
      Event = " ",
      Field = " ",
      File = " ",
      Folder = " ",
      Function = " ",
      Interface = " ",
      Key = " ",
      Keyword = " ",
      Method = " ",
      Module = " ",
      Namespace = " ",
      Null = "ﳠ ",
      Number = " ",
      Object = " ",
      Operator = " ",
      Package = " ",
      Property = " ",
      Reference = " ",
      Snippet = " ",
      String = " ",
      Struct = " ",
      Text = " ",
      TypeParameter = " ",
      Unit = " ",
      Value = " ",
      Variable = " ",
    },
  },
}

vim.g.walcriz = vim.tbl_deep_extend("force", cfg, vim.g.walcriz or {})
